apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: dashboard
spec:
  type: NodePort
  selector:
    app: dashboard
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 8081