apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dashboard-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fcavarzare/dashboard.git
    targetRevision: main
    path: deploy/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dashboard-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true